version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend/spaceObackend2
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root

  AfterInstall:
   - location: scripts/after_install.sh
     timeout: 900
     runas: root

ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 600
      runas: root