module.exports = {
    SUCCESS: 200,
    FAIL: 0,
    BAD_REQUEST: 400,
    PAGE_NOT_FOUND: 404,
    ACTIVE: 1,
    INACTIVE: 0,
    DELETE: 2,
    INTERNAL_SERVER: 500,
    PER_PAGE: 10,
    DEFAULT_PAGE: 1,
    NOT_VERIFIED: 0,
    VERIFIED: 1,
}
